#!/bin/sh
#
# Steps:
# 1) Rename starting with a numeric [0-9] and place into a subscriber directory
# 2) Implement the install function.  Use the LSB RC codes at the bottom.
# 3) Implement any other optional function.

RC_NOT_IMPLEMENTED=3
RC_INSTALL_ONLY=200

install() {
    sudo -i -u ec2-user npm install daring-http-redirector
    return $?
}
upgrade() {
    sudo -i -u ec2-user npm update
    return $?
}

start() {
    iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 5080
    iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 5443

    sudo -i -u ec2-user ./node_modules/forever/bin/forever start node_modules/daring-http-redirector/redirector.js
    return $?
}
stop() {
    sudo -i -u ec2-user ./node_modules/forever/bin/forever stopall
    return $?
}
status() {
    sudo -i -u ec2-user ./node_modules/forever/bin/forever list
    return $?
}
restart() {
    if stop
    then
        sleep 3
        start
        return $?
    else
        return $?
    fi
}

installStart() {
    start
    return $?
}
installStop() {
    stop
    return $?
}

case "$1" in
    install)
        install
        RETVAL=$?
	;;
	upgrade)
	    upgrade
	    RETVAL=$?
	;;
    install-start)
        installStart
        RETVAL=$?
    ;;
    install-stop)
        installStart
        RETVAL=$?
	;;
	start)
        start
        RETVAL=$?
    ;;
    stop)
        stop
        RETVAL=$?
	;;
	restart)
        restart
        RETVAL=$?
    ;;
    status)
        status
        RETVAL=$?
	;;
    *)
        echo "$0: $1 option not implemented"
        echo "Usage: $0 {install|upgrade|start|stop|restart|status}"
        RETVAL=3
	;;
esac

exit ${RETVAL}

# LSB RC (Return Codes) for all commands but status:
# 0	 - success
# 1  - generic or unspecified error
# 2  - invalid or excess argument(s)
# 3  - unimplemented feature (e.g. "reload")
# 4  - user had insufficient privileges
# 5  - program is not installed
# 6  - program is not configured
# 7  - program is not running
# 8--199  - reserved (8--99 LSB, 100--149 distrib, 150--199 appl)
#
# Note that starting an already running service, stopping
# or restarting a not-running service as well as the restart
# with force-reload (in case signaling is not supported) are
# considered a success.
#
# LSB RC for status command:
# 0 - service up and running
# 1 - service dead, but /var/run/  pid  file exists
# 2 - service dead, but /var/lock/ lock file exists
# 3 - service not running (unused)
# 4 - service status unknown :-(
# 5--199 reserved (5--99 LSB, 100--149 distro, 150--199 appl.)