#!/usr/bin/env sh


export AWS_DEFAULT_REGION=$(curl -s --connect-timeout 3 -s http://169.254.169.254/latest/dynamic/instance-identity/document/ | perl -ne '/region"\s+:\s+"([^"]+)/ && print $1')

aws ec2 describe-tags --filters "Name=resource-id,Values=$(my-ec2 instance-id)" --query "Tags[].[Key,Value]" --output text |
    while read TAG VALUES
    do
        ls -d [0-9]*${TAG} ${TAG} 2>/dev/null
        for VALUE in $( echo $VALUES |  perl -pe 's/\s+|,/ /g' )
        do
            ls -d [0-9]*${TAG}-${VALUE}  ${TAG}-${VALUE} 2>/dev/null
        done
    done

exit 0