#!/usr/bin/env sh

# Subscribe based on EC2 Tags or shell VARIABLES

export AWS_DEFAULT_REGION=$(curl -s --connect-timeout 3 -s http://169.254.169.254/latest/dynamic/instance-identity/document/ | perl -ne '/region"\s+:\s+"([^"]+)/ && print $1')

# AWS Tag or variable
aws ec2 describe-tags --filters "Name=resource-id,Values=$(my-ec2 instance-id)" --query "Tags[].[Key,Value]" --output text |
    while read TAG VALUES
    do
        ls -d [0-9]*${TAG} ${TAG} 2>/dev/null
        for VALUE in $( echo $VALUES |  perl -pe 's/\s+|,/ /g' )
        do
            ls -d [0-9]*${TAG}-${VALUE}  ${TAG}-${VALUE} 2>/dev/null
        done
    done

# TODO support ENV variables
# 1) save ENV variables to /etc/default/dare-sm on first pass for future runs
# 2) add function to used by all subscriptions to get EC2 Tag or ENV Variable
#set -o posix ; set | perl -pe 's/=/ /' |
#    while read TAG VALUES
#    do
#        ls -d [0-9]*${TAG} ${TAG} 2>/dev/null
#        for VALUE in $( echo $VALUES |  perl -pe 's/\s+|,/ /g' )
#        do
#            ls -d [0-9]*${TAG}-${VALUE}  ${TAG}-${VALUE} 2>/dev/null
#        done
#    done

exit 0