#!/usr/bin/env bash

if REGION=$(curl --connect-timeout 3 -s http://169.254.169.254/latest/dynamic/instance-identity/document/ | perl -ne '/region"\s+:\s+"([^"]+)/ && print $1')
then
    echo $REGION
    exit 0
else
    # exit with non-0 to trim path
    exit 1
fi