#!/usr/bin/env bash

if [[ -f /sbin/systemctl ]]
then
    echo systemd
elif [[ -f /sbin/chkconfig && -f /sbin/status && -f /sbin/start ]]
then
    echo init-chkconfig
fi

if [[ -f /sbin/status && -f /sbin/start ]]
then
    echo init
fi
